name: Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
  # https://github.com/actions/runner/issues/691
  configure:
    runs-on: ubuntu-22.04
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
      user_name: ${{ steps.get-user-name.outputs.user_name }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
      - id: get-user-name
        run: echo "user_name=$(whoami)" >> $GITHUB_OUTPUT
  test:
    name: Run tests
    needs: configure
    runs-on: ubuntu-22.04
    container:
      image: mvukov/bazel-builder:commit-8b1d07f800cc2b9a47a010da5b42c3f29294506e
      options: --user ${{ needs.configure.outputs.uid_gid }}
    env:
      BUILDBUDDY_ORG_API_KEY: ${{ secrets.BUILDBUDDY_ORG_API_KEY }}

    # Run bazel test with gcc and clang in each workspace
    strategy:
      matrix:
        folder:
          - "."
          - "examples"
        toolchain:
          - "gcc"
          - "clang"
        include:
          - toolchain: "gcc"
            config_option: ""
          - toolchain: "clang"
            config_option: "--config=clang"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Use BuildBuddy RW API key instead of public readonly key
        run: sed -i.bak 's#x-buildbuddy-api-key=.*#x-buildbuddy-api-key=${{ env.BUILDBUDDY_ORG_API_KEY }}#' .bazelrc
        if: ${{ env.BUILDBUDDY_ORG_API_KEY }}

      - name: bazel test //...
        env:
          USER: ${{ needs.configure.outputs.user_name }}
        working-directory: ${{ matrix.folder }}
        run: bazel test --config=ci ${{ matrix.config_option }} //...
